name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Generate Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Deps
        run: pnpm install

      - name: Build
        run: pnpm run build
      
      - name: Pack Crx
        run: pnpm run pack:crx

      - name: Pack Xpi
        run: pnpm run pack:xpi
      
      - uses: actions/upload-artifact@v3
        with:
          name: google-chrome-extension
          path: extension.crx
      
      - uses: actions/upload-artifact@v3
        with:
          name: firefox-extension
          path: extension.xpi
