name: Google Chrome build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Generate Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps
        run: pnpm install

      - name: Build
        run: pnpm run build
      
      - name: Pack
        run: pnpm run  pack:crx
