name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Generate Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Pack Crx
        run: npm run pack:crx

      - name: Pack Xpi
        run: npm run pack:xpi

      # - name: Create release
      #   uses: Roang-zero1/github-create-release-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      # - name: Upload release artifacts
      #   uses: Roang-zero1/github-upload-release-artifacts-action@v2
      #   with:
      #     args: "dist/bin/ dist/shell/compiled.sh"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN  }}

      - name: upload chrome artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.crx
          asset_name: subtitles-on-modal-chrome.crx
          asset_content_type: application/gzip

      - name: upload firefox artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.xpi
          asset_name: subtitles-on-modal-firefox.xpi
          asset_content_type: application/gzip
