name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Generate Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Deps
        run: pnpm install

      - name: Build
        run: pnpm run build
      
      - name: Pack Crx
        run: pnpm run pack:crx

      - name: Pack Xpi
        run: pnpm run pack:xpi
      
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload firefox artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.xpi
          asset_name: subtitles-on-modal-firefox.xpi
          asset_content_type: application/gzip